export const ADVERT_LIST_REQUEST = "ADVERT_LIST_REQUEST";
export const ADVERT_LIST_SUCCESS = "ADVERT_LIST_SUCCESS";
export const ADVERT_LIST_FAIL = "ADVERT_LIST_FAIL";

export const USER_ADVERT_LIST_REQUEST = "USER_ADVERT_LIST_REQUEST";
export const USER_ADVERT_LIST_SUCCESS = "USER_ADVERT_LIST_SUCCESS";
export const USER_ADVERT_LIST_FAIL = "USER_ADVERT_LIST_FAIL";

export const ADVERT_DETAILS_REQUEST = "ADVERT_DETAILS_REQUEST";
export const ADVERT_DETAILS_SUCCESS = "ADVERT_DETAILS_SUCCESS";
export const ADVERT_DETAILS_FAIL = "ADVERT_DETAILS_FAIL";

export const ADVERT_CREATE_REQUEST = "ADVERT_CREATE_REQUEST";
export const ADVERT_CREATE_SUCCESS = "ADVERT_CREATE_SUCCESS";
export const ADVERT_CREATE_FAIL = "ADVERT_CREATE_FAIL";
export const ADVERT_CREATE_RESET = "ADVERT_CREATE_RESET";

export const ADVERT_UPDATE_REQUEST = "ADVERT_UPDATE_REQUEST";
export const ADVERT_UPDATE_SUCCESS = "ADVERT_UPDATE_SUCCESS";
export const ADVERT_UPDATE_FAIL = "ADVERT_UPDATE_FAIL";
export const ADVERT_UPDATE_RESET = "ADVERT_UPDATE_RESET";

export const ADVERT_DELETE_REQUEST = "ADVERT_DELETE_REQUEST";
export const ADVERT_DELETE_SUCCESS = "ADVERT_DELETE_SUCCESS";
export const ADVERT_DELETE_FAIL = "ADVERT_DELETE_FAIL";
export const ADVERT_DELETE_RESET = "ADVERT_DELETE_RESET";
